### ISSUE TITLE
Can you provide the import function of SolidWorks model?

### ISSUE THREAD

**Issue by WREQI** [bitbybit-dev/bitbybit#21]

**Comment by Irev-Dev** [comment]
I'm not involved with the repo at all so I can't say for certain, but I think that's probably pretty unlikely, though maybe STEP import is more likely which you should be able to export from SolidWorks.

**Comment by bitbybit-dev** [comment]
Hi @WREQI, thanks for opening this! OCCT will allow me to implement the import for STEP and IGES, but not for SolidWorks directly as pointed out by @Irev-Dev. I suppose SolidWorks can export to these formats, but I understand that this, depending on your use case, might be either acceptable or not.

I did not yet implement Import just yet because of a generic approach I'm taking towards asset management and this project in general. I am currently building a cloud backend for bitbybit which will allow users to create, share and remix projects of others. This will also allow them to persist assets in cloud storage associated to their projects so that you would not need to re-import those files every time you restart the browser. In principle this will work for step, iges, obj, stl, txt and other formats that might be needed in the future... I guess I will also cache those assets on the IndexedDB not to kill the network. This will provide a generic approach to file management on the app.

This does not mean that the whole app will be closed behind the signup, but it does mean that for those more advanced scenarios requiring persistant storage and a database you would need an account.

I can't say exactly when this cloud integration will be finished, but I'm hoping to have first release somewhere this month. It already ate more time than I imagined, so I'm sorry that I can't make a big promise just now.

I hope this answers the question for now. When I'll have more info about Importing assets I will update this thread.

**Comment by bitbybit-dev** [comment]
Hi @WREQI and @Irev-Dev, it took a while and I'm not sure if this is still relevant to you, but with the latest release we support import of assets in STEP and IGES file formats. I know it's not direct Solidworks support, but I've prepared a short video showing how STEP exports/imports work between Rhino and Bit by bit.

https://www.youtube.com/watch?v=TTAsTwruDNU

Also be aware that large files having a lot of faces can take a long time to load or even crash the browser ;) I'll be looking at performance improvements a bit later.
