### ISSUE TITLE
website broken

### ISSUE THREAD

**Issue by unicomp21** [bitbybit-dev/bitbybit#29]
for some reason https://bitbybit.dev/ doesn't seem to run in brave browser?  whenever i click on a link, it won't navigate to the next page.

can we enable discussions on this repo?

**Comment by bitbybit-dev** [comment]
Hi, sure we can discuss it here, thanks for reporting. I installed Brave browser on my iphone and mac, the website and examples seem to function well with default settings. I tested private windows with cookies disabled and that worked also. I also tested with Tor enabled - it was indeed much slower, but at the end when resources loaded it did work. I made a small recording [video](https://app.bitbybit.dev/assets/brave.mov).

I have few theories though - when the website is loaded for the first time, on the bottom of the screen we show a modal to accept or decline cookies. While this modal is not clicked, the website is behind a backdrop that is non-clickable. Might it be that you somehow did not see that modal for cookies? In case you missed it we'll need to make this more prominent or there might have been some problem with our css.

If only examples would not work for you I would suspect our wasm module, which is memory hungry beast, but the homepage of https://bitbybit.dev website itself is not depending on it, only the htpps://bitbybit.dev/app and examples. I only have iphone 13 to test out the mobile devices and I know that on devices that do not have as much RAM browsers would generally simply reload few times and throw an error to the user when our wasm module consumes too much memory.

I would really love to solve this, but if it was not caused by that cookie modal I may need more info on your device / operating system. If you could provide a screenshot of the brave console (in case it shows some errors) that would be great. It might also be that there are other security settings which my website may break for you. I wonder if the website works for you on other browsers. It might be that this is not browser related issue after all. Any additional info would be great. Thanks!

**Comment by unicomp21** [comment]
Do you have this enabled?

https://www.ghacks.net/2022/10/01/how-to-enable-braves-upcoming-cookie-consent-blocking-feature-right-now/

**Comment by bitbybit-dev** [comment]
I did not try that indeed. Now that I did try it I could reproduce the problem and fix it. Brave was indeed clicking away the modal, but javascript probably didn't have enough time to pick it up and remove the backdrop. Backdrop is now removed and buttons are clickable. Hope this will work for you also :) Thanks a lot for reporting this! Also a nice feature of brave.

**Comment by unicomp21** [comment]
Works perfectly now, thanks!
